"""empty message

Revision ID: 37ab2cd7a4da
Revises: df60487c3cd2
Create Date: 2023-02-24 16:51:11.768721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ab2cd7a4da'
down_revision = 'df60487c3cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite_planets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.planet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.create_table('favorite_vehicles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vehicle_id')
    )
    op.create_table('favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.drop_table('users')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('planet_from',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('characters_name_key', type_='unique')
        batch_op.drop_constraint('characters_planet_from_key', type_='unique')
        batch_op.create_foreign_key(None, 'planets', ['planet_from'], ['planet_id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_constraint('vehicles_vehicle_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('vehicles_vehicle_id_key', ['vehicle_id'])
        batch_op.alter_column('crew',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('characters_planet_from_key', ['planet_from'])
        batch_op.create_unique_constraint('characters_name_key', ['name'])
        batch_op.alter_column('birth_year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('planet_from',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               nullable=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_table('favorite_characters')
    op.drop_table('favorite_vehicles')
    op.drop_table('favorite_planets')
    op.drop_table('user')
    # ### end Alembic commands ###
